package com.spulido.tfg.domain.alerts.model;

import java.time.Instant;
import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an event that can trigger alerts.
 * Events are generated by various system operations (scans, remediations, etc.).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AlertEvent {

    /**
     * Type of event that occurred
     */
    private AlertEventType type;

    /**
     * Severity level (for vulnerability events)
     */
    private String severity;

    /**
     * Additional event payload/metadata
     */
    private Map<String, Object> payload;

    /**
     * When the event occurred
     */
    private Instant timestamp;

    /**
     * Organization ID for scoping
     */
    private String organizationId;

    /**
     * Project ID for scoping
     */
    private String projectId;

    public enum AlertEventType {
        VULNERABILITY_DETECTED,
        REMEDIATION_COMPLETED,
        SCAN_COMPLETED
    }
}
