package com.spulido.tfg.domain.alerts.model;

/**
 * Enum representing the conditions that trigger an alert.
 * These conditions are matched against events generated by the system.
 */
public enum WhenCondition {
    /**
     * Triggered when any vulnerability is detected in a scan report.
     */
    ON_VULNERABILITY_DETECTED,

    /**
     * Triggered when a high severity vulnerability is detected (CVSS >= 7.0 or severity HIGH/CRITICAL).
     */
    ON_HIGH_SEVERITY_VULNERABILITY,

    /**
     * Triggered when a remediation action completes successfully.
     */
    ON_REMEDIATION_SUCCESS,

    /**
     * Triggered when a remediation action fails.
     */
    ON_REMEDIATION_FAILURE,

    /**
     * Triggered when a scheduled scan completes (with or without findings).
     */
    ON_SCAN_COMPLETED
}
