spring.application.name=agent
server.port=1222

agent.central-url=http://localhost:8080
agent.api-key=${AGENT_API_KEY:}
agent.agent-id=${AGENT_ID:}
agent.central-public-key=${CENTRAL_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqlgP3qn1Z4WtddOsRPio\nJK1yxr1fJc8DcfpL6fDYHwKUN+yggkHdpEqzUcM+XklMEnlx7c+zEeXgJIynzq/r\nWOd4tR0gKWwAepZK/Fzms+i0Ty2rmiIbkFw8vNPLKVIFsHnHEtSdUyLYQYvWsSqP\n4gc/niHzgimGMONGT8Wr4kifWbeVATGmE27YW4tErtVr9zrf9x6SYIkKfo2Xx+Ee\n/KYU9gW5TyWcDHyEv443+5jA0ctcOMKgipgZwTGihlzNGgkwhSbdUg2DXKa0UrpS\nmdLM2XvyD3+bxiUu0LvhHQSMIDCg3L339J8dwQVaxVPy25ipk19eLa+XxkAwYKHe\nJwIDAQAB\n-----END PUBLIC KEY-----}

agent.exploit.default-target-user=root
agent.exploit.transfer-method=auto
agent.exploit.transfer-method.retries=3
agent.exploit.transfer-file-max-size-mb=100