spring.application.name=agent
server.port=1222

agent.central-url=http://localhost:8080
agent.api-key=${AGENT_API_KEY:}
agent.agent-id=${AGENT_ID:}
agent.central-public-key=${CENTRAL_PUBLIC_KEY:}

agent.exploit.default-target-user=root
agent.exploit.transfer-method=auto
agent.exploit.transfer-method.retries=3
agent.exploit.transfer-file-max-size-mb=100