package com.spulido.tfg.domain.report.model;

/**
 * How a report was produced.
 * <ul>
 *   <li>ON_DEMAND: generated by an administrator through the UI</li>
 *   <li>SCHEDULED: generated automatically by the scheduled generator</li>
 * </ul>
 */
public enum GenerationType {
    ON_DEMAND,
    SCHEDULED
}
