package com.spulido.tfg.domain.plan.model;

public enum StepAction {
    SYSTEM_SCAN,
    SERVICE_SCAN,
    NETWORK_SCAN,
    GENERATE_REPORT,
    SEND_REPORT,
    EXPLOITATION_KNOWLEDGE,
    REQUEST_REPLICATION,
    EXECUTE_EXPLOIT,
    TRANSFER_AGENT,
    REPLICATE,
    SELF_DESTRUCT
}
